spring.application.name=${SPRING_APPLICATION_NAME:payment-service}
server.port=${SERVER_PORT:8086}

# Stripe Configuration - matching what the service expects
stripe.secretKey=${STRIPE_SECRET_KEY:sk_test_51S0Ek1I3yWYzz2McGSNsNUEtsmz0ywePckU8dwA4GPIEAYiRebvNFSnAj7fVs4vJLwgJ8zQh1MKL5XiAYlJ9O0od00u79PRnr4}



# Logging Configuration
logging.level.root=INFO
logging.level.com.stripe=DEBUG
